# opt-in to Travis new container-based infrastructure
sudo: false

# cache stuff, hopefully shortening build times
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

jdk: oraclejdk8
language: scala
scala:
  - 2.11.7
script:
  - "sbt scalastyle"
  - "sbt coffeelint"
  - "sbt test"
